"""Smart Crop regression: busy camera paths must still give FFmpeg a valid crop expression.

Run:  .venv\\Scripts\\python -m unittest discover tests
"""
import math
import subprocess
import unittest

from shortsforge.facetrack import x_expression
from shortsforge.renderer import _camera_at
from shortsforge.utils import ToolMissing, find_ffmpeg


def busy_path(n: int) -> list:
    """A camera that moves every 0.25 s (like a fast IRL stream), n keyframes."""
    return [(i * 0.25, 300 + 250 * math.sin(i * 1.3)) for i in range(n)]


def eval_x(expr: str, t: float) -> float:
    # the expression is generated by x_expression from numbers above (never outside input), and its
    # FFmpeg syntax (gte/lt, + - * and parentheses) is also valid Python
    return eval(expr, {"gte": lambda a, b: float(a >= b), "lt": lambda a, b: float(a < b), "t": t})


class XExpressionTest(unittest.TestCase):
    def test_values_follow_the_camera_path(self):
        path = busy_path(150)
        expr = x_expression(path)
        for t in (0.0, 0.1, 5.37, 20.0, 37.2):
            self.assertAlmostEqual(eval_x(expr, t), _camera_at(path, t), delta=0.6)

    def test_ffmpeg_accepts_many_camera_moves(self):
        # 98+ moves used to fail with "Failed to configure input pad on Parsed_crop" (-22, Invalid argument)
        try:
            ff = find_ffmpeg()
        except ToolMissing:
            self.skipTest("ffmpeg not installed")
        expr = x_expression(busy_path(400))
        r = subprocess.run([ff, "-v", "error", "-f", "lavfi", "-i", "testsrc2=s=1920x1080:r=30:d=0.3",
                            "-vf", f"crop=w=606:h=1080:x='{expr}':y=0", "-f", "null", "-"],
                           capture_output=True, text=True)
        self.assertNotIn("Invalid argument", r.stderr)
        self.assertEqual(r.returncode, 0, r.stderr[-500:])


if __name__ == "__main__":
    unittest.main()
